naming:
  ConstructorParameterNaming:
    excludes:
      - '**/TreeNode.kt'

formatting:
  MaximumLineLength:
    excludes:
      - '**/*Test.kt'

style:
  MaxLineLength:
    excludes:
      - '**/*Test.kt'
  ReturnCount:
    max: 3
